version: 2
jobs:
  build:
    docker:
      - image: oracle/graalvm-ce:latest
    environment:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-dependencies-native
      - run: ./gradlew shadowJar
      - run: ./gradlew nativeImage
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-dependencies-native
      - store_artifacts:
          path: build/libs
      - store_artifacts:
          path: build/graal
