version: 2
jobs:
  build:
    docker:
      - image: oracle/graalvm-ce:19.1.1
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-dependencies
      - run: ./gradlew --no-daemon shadowJar
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-dependencies
      - run: gu install native-image
      - run: cd build/libs && find . -name "*.jar" -exec native-image -jar \{\} \; && find . -name "*-fat" -exec mv \{\} adr \;
      - store_artifacts:
          path: build/libs
